spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  redis:
    host: redis
    port: 6379
    
  ai:
    vertex:
      ai:
        gemini:
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash
    
logging:
  level:
    com.compass: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG