spring:
  datasource:
    url: jdbc:postgresql://compass-db.ch6mum0221cb.ap-northeast-2.rds.amazonaws.com:5432/compass
    username: compass
    password: compass1004!
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      pool-name: CompassHikariPool

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

  security:
    jwt:
      secret: ${JWT_SECRET}
      refresh-secret: ${JWT_SECRET}
      access-expiration: 86400000
      refresh-expiration: 604800000

logging:
  level:
    com.compass: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.zaxxer.hikari: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

aws:
  s3:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}

api:
  perplexity:
    key: ${PERPLEXITY_API_KEY}
  tour:
    key: ${TOUR_API_KEY}

# 외부 API 키
TOUR_API_KEY: ${TOUR_API_KEY}
PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
AWS_S3_REGION: ${AWS_S3_REGION}

server:
  port: 8080
  tomcat:
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10