spring:
  application:
    name: compass-backend
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:compass}
    username: ${DB_USERNAME:compass_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    prefix:
      verification: "verification:"
    
  security:
    jwt:
      access-secret: ${JWT_ACCESS_SECRET:your-256-bit-secret-key-for-access-token}
      refresh-secret: ${JWT_REFRESH_SECRET:your-256-bit-secret-key-for-refresh-token}
      access-expiration: 3600000  # 1 hour
      refresh-expiration: 604800000  # 7 days

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:your-gmail-username@gmail.com} # 실제 Gmail 계정
    password: ${GMAIL_APP_PASSWORD:your-gmail-app-password}   # Gmail 2단계 인증 후 생성한 앱 비밀번호
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      
logging:
  level:
    com.compass: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG