spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/compass
    username: compass_user
    password: compass_password
    
  redis:
    host: redis
    port: 6379
    
  ai:
    vertex:
      ai:
        gemini:
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash
    
logging:
  level:
    com.compass: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN