name: Environment Setup Helper

on:
  workflow_dispatch:
    inputs:
      setup_type:
        description: 'Setup type'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - test
          - production

jobs:
  generate-env:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Generate .env file from secrets
      run: |
        cat > .env << EOF
        # Database Configuration
        DB_HOST=localhost
        DB_PORT=5432
        DB_NAME=compass
        DB_USERNAME=compass_user
        DB_PASSWORD=compass_password
        
        # Redis Configuration
        REDIS_HOST=localhost
        REDIS_PORT=6379
        REDIS_PASSWORD=
        
        # JWT Configuration
        JWT_ACCESS_SECRET=dev-jwt-access-secret-key-change-in-production-256bits
        JWT_REFRESH_SECRET=dev-jwt-refresh-secret-key-change-in-production-256bits
        JWT_ACCESS_TOKEN_EXPIRY=3600000
        JWT_REFRESH_TOKEN_EXPIRY=604800000
        
        # Spring AI - OpenAI Configuration
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL=gpt-4o-mini
        OPENAI_TEMPERATURE=0.7
        
        # Spring AI - Google Gemini Configuration
        GOOGLE_CREDENTIALS_BASE64=${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        GOOGLE_CLOUD_LOCATION=${{ secrets.GOOGLE_CLOUD_LOCATION }}
        GEMINI_MODEL=gemini-2.0-flash-exp
        GEMINI_TEMPERATURE=0.7
        
        # Application Configuration
        SERVER_PORT=8080
        SPRING_PROFILES_ACTIVE=${{ github.event.inputs.setup_type }}
        
        # Logging Configuration
        LOGGING_LEVEL_ROOT=INFO
        LOGGING_LEVEL_COM_COMPASS=DEBUG
        
        # CORS Configuration
        CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
        CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
        CORS_ALLOWED_HEADERS=*
        CORS_ALLOW_CREDENTIALS=true
        EOF
        
        echo "✅ .env file generated successfully"
    
    - name: Upload .env as artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-file-${{ github.event.inputs.setup_type }}
        path: .env
        retention-days: 1
    
    - name: Display instructions
      run: |
        echo "==============================================="
        echo "✅ Environment file has been generated!"
        echo "==============================================="
        echo ""
        echo "To download the .env file:"
        echo "1. Go to the Actions tab"
        echo "2. Click on this workflow run"
        echo "3. Download the 'env-file-${{ github.event.inputs.setup_type }}' artifact"
        echo "4. Extract and place the .env file in your project root"
        echo ""
        echo "Note: The artifact will be automatically deleted after 1 day for security."
